name: multiple-event-workflow
on: # push, issue가 생성, 수동 트리거 될 경우 워크플로우 트리거
  push:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  multiple-event-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action